name: Build ZMK firmware

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout user config
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip git cmake ninja-build gperf ccache dfu-util wget \
            device-tree-compiler libncurses-dev flex bison libffi-dev libssl-dev \
            python3-dev python3-setuptools python3-wheel xz-utils file make gcc g++ \
            unzip tar zlib1g-dev

      - name: Clone ZMK fork
        run: |
          git clone https://github.com/Michael5898/zmk
          cd zmk
          west init -l app
          west update
          west zephyr-export
          pip3 install -r zmk/app/requirements.txt

      - name: Build firmware
        run: |
          west build -s zmk/app -b nice_nano_v2 -- -DZMK_CONFIG=${{ github.workspace }}
